#!/usr/bin/env bash 

uname_os() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  echo "$os"
}

uname_arch() {
  arch=$(uname -m)
  case $arch in
    x86) arch="386" ;;
    i686) arch="386" ;;
    i386) arch="386" ;;
    aarch64) arch="arm64" ;;
    armv5*) arch="armv5" ;;
    armv6*) arch="armv6" ;;
    armv7*) arch="armv7" ;;
  esac
  echo ${arch}
}


# Tailwindcss
install_tailwind(){
  local os=$(uname_os)
  local arch=$(uname_arch)

  case "$os" in
    darwin*) os="macos" ;;
  esac

  case "$arch" in
    aarch64) arch="arm64" ;;
    x86_64) arch="x64" ;;
  esac

  binary_name="tailwindcss-${os}-${arch}"
  curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/${binary_name}
  chmod +x ./${binary_name}
  mv ${binary_name} ./bin/tailwindcss
}


# Pagefind
install_pagefind(){
  url=''

  local arch=$(uname_arch)
  local os=$(uname_os)

  case "$arch" in
    arm64) arch="aarch64" ;;
  esac

  if [ $os = 'darwin' ]; then
      url="https://github.com/CloudCannon/pagefind/releases/download/v0.12.0/pagefind-v0.12.0-${arch}-apple-darwin.tar.gz"
  else 
      url="https://github.com/CloudCannon/pagefind/releases/download/v0.12.0/pagefind-v0.12.0-${arch}-unknown-linux-musl.tar.gz"
  fi

  curl -sL -o pagefind.tar.gz ${url} 
  tar -xvzf pagefind.tar.gz
  chmod +x ./pagefind
  mv ./pagefind ./bin/pagefind
  rm pagefind.tar.gz
}

#alvu
install_alvu(){
  curl -sLf https://goblin.run/github.com/barelyhuman/alvu | PREFIX=./bin sh
  chmod +x ./bin/alvu
}

mkdir -p ./bin

install_tailwind
install_pagefind
install_alvu