#!/usr/bin/env bash 

set -euxo pipefail

curl -o alvu.tgz -L https://codeberg.org/attachments/4f777ba1-a1cf-46cd-8a4e-c38115c66dd5
tar -xvzf alvu.tgz
install linux-amd64/alvu /usr/local/bin

alvu --hard-wrap=false