#!/usr/bin/env bash 

set -euxo pipefail

curl -o alvu.tgz -L https://github.com/barelyhuman/alvu/releases/download/v0.2.8/linux-amd64.tgz
tar -xvzf alvu.tgz
install linux-amd64/alvu /usr/local/bin

make build
