#!/usr/bin/env bash 

set -euxo pipefail

mkdir -p ./bin

curl -sf https://goblin.run/github.com/barelyhuman/alvu | PREFIX=./bin sh
curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
chmod +x ./tailwindcss-linux-x64
mv tailwindcss-linux-x64 ./bin/tailwindcss

make build
